#! /usr/bin/env python3

import os
import requests

dataDirectory = "/data/feedback"
addy = "http://35.232.246.214/feedback"
feedback = {}
keys = ("title", "name", "date", "feedback")

for fileItem in os.listdir(dataDirectory):
  feedback[fileItem] = {}
  with open(dataDirectory + fileItem) as f:
    listItem = (zip(keys,f))
    feedback[fileItem] = dict(listItem)
   
for key in feedback:
  r = requests.post(addy, data = feedbak[key])
  if 199 < r.status_code < 300:
    print("Successful request")
  else:
    print(r.raise_for_status())
